---
# Project Information
site_name: PyCommons Lang
site_author: Shashank Sharma
site_description: Python Commons Lang

# Repository information
repo_name: shashankrnr32/pycommons-lang
repo_url: https://github.com/PyCommons/pycommons-lang
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Shashank Sharma

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shashankrnr32
      name: shashankrnr32 on GitHub

# Page tree
nav:
  - Home: index.md
