---
name: Docs publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Poetry
        run: pip install mkdocs-material
      - name: Install dependencies
        run: poetry update
      - name: Deploy Documentation
        run: mkdocs gh-deploy --force
